services:
  origin:
    build: origin
    volumes:
      - "./origin/http.conf:/usr/local/openresty/nginx/conf/nginx.conf"
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    build: api
    ports:
      - "8081:8081"
